version: '3.8'

services:

  mongo:
    image: mongo:6.0
    container_name: innodelivery_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: innodelivery_clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  mongo_data:
  clickhouse_data: