[package]
name = "user_service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = {version = "4.0.1", features = ["macros"]}
dotenv = "0.15.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
jsonwebtoken = "8.2.0"
argon2 = "0.4.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
rand = { version = "0.8", features = ["getrandom"] }
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "uuid", "chrono"] }
chrono = { version = "0.4.23", features = ["serde"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
lazy_static = "1.4.0"
fake = { version = "2.9", features = ["chrono"] }
diesel_migrations = { version = "2.1.0", features = ["postgres"] }
url = "2.5.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
validator = { version = "0.15.0", features = ["derive"] }
bcrypt = "0.12.0"