name: innoDelivery quality check

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  quality_check:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgres://admin:admin_password@localhost:5434/inno_delivery_test
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_PHONE: ${{ secrets.ADMIN_PHONE }}
      ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
      DATABASE_URL_ORDER_TEST: postgres://admin:admin_password@localhost:5436/inno_delivery_order_test
      RUST_TEST_THREADS: 1


    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin_password
          POSTGRES_DB: inno_delivery_test
        ports:
          - 5434:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      order_postgres_test:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin_password
          POSTGRES_DB: inno_delivery_order_test
        ports:
          - 5436:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: . -> target

      - name: Check formatting (Root Workspace)
        run: cargo fmt -- --check

      - name: Run Clippy linter (Root Workspace)
        run: cargo clippy --all-targets --

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run tests with tarpaulin for order_service
        run: cargo tarpaulin -p order_service --out Html --output-dir coverage

      - name: Run tests with tarpaulin for user_service
        run: cargo tarpaulin -p user_service --out Html --output-dir coverage

      - name: Upload services coverage report
        uses: actions/upload-artifact@v4
        with:
          name: services-coverage
          path: coverage
